repos:
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.4.2
  hooks:
    - id: style-files
      args: [--style_pkg=styler, --style_fun=tidyverse_style]
      require_serial: true
    - id: lintr
    - id: parsable-R
    - id: no-browser-statement
    - id: no-debug-statement
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=250']
    - id: mixed-line-ending
      args: ['--fix=no']
    - id: trailing-whitespace
      exclude: activate.R
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.0
  hooks:
    # Python linter. Ruff recommends running this before the formatter to
    # avoid conflicts when using the --fix flag
    - id: ruff
      args:
        - --fix
    # Formatter
    - id: ruff-format
- repo: local
  hooks:
    - id: forbid-to-commit
      name: Don't commit common R artifacts
      entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
      language: fail
      files: '\.(Rhistory|RData|Rds|rds)$'
