name: generate-pinval

on:
  workflow_dispatch:
    inputs:
      year:
        type: string
        description: >
          Assessment year: Use values and comps from the final model for this year.
          Leave blank if you are supplying a run ID instead
        required: false
        default: "2025"

      run_id:
        type: string
        description: >
          Run ID: The model run whose comps should be used. Leave blank if you are supplying
          an assessment year instead
        required: false
        default: ""

      pins:
        type: string
        description: >
          PINs: One or more comma‑separated Cook County PINs. Leave blank to
          generate reports for all PINs in the assessment triad
        required: false
        default: ""

      environment:
        type: choice
        description: >
          Environment: Choose where to upload the reports
        options:
          - Development bucket
          - Production bucket
        default: Development bucket
        required: true

env:
  PYTHONUNBUFFERED: "1"
  UV_SYSTEM_PYTHON: 1
  AWS_REGION: us-east-1
  AWS_ATHENA_S3_STAGING_DIR: s3://ccao-athena-results-us-east-1/
  HUGO_VERSION: "0.147.5"

jobs:
###############################################################################
# Setup
###############################################################################
  setup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      matrix: ${{ steps.resolve-metadata.outputs.matrix }}
      count: ${{ steps.resolve-metadata.outputs.count }}
      assessment-year: ${{ steps.resolve-metadata.outputs.assessment-year }}
      run-id: ${{ steps.resolve-metadata.outputs.run-id }}
      triad: ${{ steps.resolve-metadata.outputs.triad }}
      pins: ${{ steps.clean-pins.outputs.pins }}
      invalidation-paths: ${{ steps.clean-pins.outputs.invalidation-paths }}
      bucket: ${{ steps.resolve-aws.outputs.bucket }}
      distribution-id: ${{ steps.resolve-aws.outputs.distribution-id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mask sensitive information
        shell: bash
        run: echo "::add-mask::${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: scripts/generate_pinval/uv.lock

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: scripts/generate_pinval/.python-version

      - name: Install Python requirements
        shell: bash
        run: uv pip install .
        working-directory: scripts/generate_pinval

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          aws-region: us-east-1

      - name: Resolve model metadata
        id: resolve-metadata
        shell: bash
        run: |
          python3 scripts/generate_pinval/resolve_model_metadata.py \
            --year "${{ inputs.year }}" \
            --run-id "${{ inputs.run_id }}" \
            --pins "${{ inputs.pins }}" \
            --write-github-output

      - name: Clean PINs
        id: clean-pins
        shell: bash
        env:
          YEAR: ${{ steps.resolve-metadata.outputs.assessment-year }}
        run: |
          # Convert PINs to array so that we can convert the delimiter from
          # comma to space for use in script args, and output S3 paths
          # for cache invalidation
          IFS=' ' read -ra PINS_ARR <<< "${{ inputs.pins }}"
          CLEAN_PINS=()
          for p in "${PINS_ARR[@]:-}"; do
            [[ -n "$p" ]] && CLEAN_PINS+=("$p")
          done

          echo "pins=${CLEAN_PINS[@]}" >> "$GITHUB_OUTPUT"

          INVALIDATION_PATHS=()
          if [[ ${#CLEAN_PINS[@]} -gt 0 ]]; then
            for pin in "${CLEAN_PINS[@]:-}"; do
              INVALIDATION_PATHS+=("/${YEAR}/${pin}.html")
            done
          else
            INVALIDATION_PATHS+=("/${YEAR}/*.html")
          fi
          echo "invalidation-paths=${INVALIDATION_PATHS[@]}" >> "$GITHUB_OUTPUT"

      - name: Resolve AWS resource IDs
        id: resolve-aws
        shell: bash
        run: |
          if [[ "${{ inputs.environment }}" == 'Development bucket' ]]; then
            echo "bucket=${{ vars.AWS_S3_BUCKET_PINVAL_STAGING }}" >> "$GITHUB_OUTPUT"
            echo "distribution-id=${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID_STAGING }}" >> "$GITHUB_OUTPUT"
          else
            echo "bucket=${{ vars.AWS_S3_BUCKET_PINVAL_PROD }}" >> "$GITHUB_OUTPUT"
            echo "distribution-id=${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID_PROD }}" >> "$GITHUB_OUTPUT"
          fi

###############################################################################
# Generate PINVAL reports for a triad or explicit PINs
###############################################################################
  generate-pinval:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      max-parallel: ${{ fromJson(needs.setup.outputs.count) }}
    env:
      TOWNSHIP: ${{ matrix.township }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mask sensitive information
        run: echo "::add-mask::${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: scripts/generate_pinval/uv.lock

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: scripts/generate_pinval/.python-version

      - name: Install Python requirements
        shell: bash
        run: uv pip install .
        working-directory: scripts/generate_pinval

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          aws-region: us-east-1

      - name: Cache Hugo package
        id: cache-hugo
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/hugo.deb
          key: hugo-deb-${{ env.HUGO_VERSION }}

      - name: Download Hugo
        if: steps.cache-hugo.outputs.cache-hit != 'true'
        shell: bash
        run: |
          wget -O ${{ runner.temp }}/hugo.deb \
            https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb

      - name: Install Hugo
        shell: bash
        run: sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Generate PINVAL reports (triad shard or explicit PINs)
        shell: bash
        env:
          RUN_ID: ${{ needs.setup.outputs.run-id }}
          PINS: ${{ needs.setup.outputs.pins }}
        run: |
          python3 scripts/generate_pinval/generate_pinval.py \
            --run-id "$RUN_ID" \
            --township "$TOWNSHIP" \
            --pin "$PINS"

      - name: Sync reports to S3
        shell: bash
        env:
          TARGET_BUCKET: ${{ needs.setup.outputs.bucket }}
          YEAR: ${{ steps.setup.outputs.assessment-year }}
        run: |
          LOCAL="hugo/public/${YEAR}/"
          REMOTE="${TARGET_BUCKET%/}/${YEAR}/"
          aws s3 sync "$LOCAL" "$REMOTE" \
            --no-progress \
            --include '*.html'

###############################################################################
# Invalidate cache and notify
###############################################################################
  notify:
    needs:
      - setup
      - generate-pinval
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          aws-region: us-east-1

      - name: Mask AWS identifiers
        shell: bash
        run: |
          echo "::add-mask::${{ secrets.AWS_ACCOUNT_ID }}"
          echo "::add-mask::${{ secrets.AWS_SNS_NOTIFICATION_TOPIC_ARN }}"

      - name: Invalidate cache
        env:
          TARGET_DISTRIBUTION_ID: ${{ steps.resolve-cloudfront.outputs.distribution-id }}
          INVALIDATION_PATHS: ${{ needs.setup.outputs.invalidation-paths }}
        shell: bash
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${TARGET_DISTRIBUTION_ID}" \
            --paths "${INVALIDATION_PATHS}"

      - name: Publish SNS notification
        env:
          RUN_ID: ${{ needs.setup.outputs.run-id }}
          YEAR: ${{ needs.setup.outputs.assessment-year }}
          TRIAD: ${{ needs.setup.outputs.triad }}
          PINS: ${{ needs.setup.outputs.pins }}
          ENV_LABEL: ${{ inputs.environment }}
          BUCKET: ${{ needs.setup.outputs.bucket }}
        shell: bash
        run: |
          SUBJECT="PINVAL reports ready for run-id $RUN_ID"
          MESSAGE=$(cat <<EOF
          Your requested PINVAL reports have been generated.

          Assessment year: $YEAR
          Run-ID: $RUN_ID
          Triad: $TRIAD
          PIN list: $PINS
          Environment: $ENV_LABEL

          You can browse or download the reports here:
          $BUCKET
          EOF
          )
          aws sns publish \
            --topic-arn "${{ secrets.AWS_SNS_NOTIFICATION_TOPIC_ARN }}" \
            --subject "$SUBJECT" \
            --message "$MESSAGE"
